const ALLOWED_ORIGINS=new Set(["https://softm.github.io","http://localhost:3000","http://127.0.0.1:3000"]);
const BASE="https://www.longtermcare.or.kr";
const DETAIL_PATH="/npbs/r/a/201/selectLtcoSrchDetail.web";
const TABS=new Map([[11,"기본정보"],[12,"평가정보"],[13,"정원/현원"],[14,"인력현황"],[15,"시설현황"],[16,"비급여비용"],[17,"프로그램"],[18,"사진"],[19,"CCTV"]]);
const cache=new Map(),buckets=new Map(),TTL=6*60*60*1000;
function cors(req,res){const origin=req.headers.origin||"";if(ALLOWED_ORIGINS.has(origin)){res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Vary","Origin")}res.setHeader("Access-Control-Allow-Methods","GET, POST, OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type")}
function rateLimited(req){const key=String(req.headers["x-forwarded-for"]||"").split(",")[0].trim()||"unknown",now=Date.now(),v=buckets.get(key);if(!v||now-v.at>60000){buckets.set(key,{at:now,count:1});return false}return++v.count>45}
const entities={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",middot:"·",ensp:" ",emsp:" "};
function decode(value=""){return value.replace(/&#(x?[0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(n[0].toLowerCase()==="x"?parseInt(n.slice(1),16):parseInt(n,10))).replace(/&([a-z]+);/gi,(m,n)=>entities[n.toLowerCase()]??m)}
function text(value=""){return decode(value.replace(/<br\s*\/?>/gi,"\n").replace(/<[^>]*>/g," ")).replace(/[ \t]+/g," ").replace(/\s*\n\s*/g,"\n").trim()}
function attr(tag,name){const m=tag.match(new RegExp(`\\s${name}\\s*=\\s*(["'])(.*?)\\1`,"i"));return m?decode(m[2]):""}
function absolute(value){try{const url=new URL(value,BASE);return url.protocol==="https:"||url.protocol==="http:"?url.href:""}catch{return""}}
function apiBase(){const host=process.env.VERCEL_PROJECT_PRODUCTION_URL||process.env.VERCEL_URL||"localhost:3000",protocol=host.startsWith("localhost")||host.startsWith("127.0.0.1")?"http":"https";return String(process.env.PUBLIC_API_BASE_URL||`${protocol}://${host}`).replace(/\/+$/,"")}
function extractTables(html){const out=[];for(const match of html.matchAll(/<table\b[^>]*>([\s\S]*?)<\/table>/gi)){const body=match[1],caption=text((body.match(/<caption\b[^>]*>([\s\S]*?)<\/caption>/i)||[])[1]||""),rows=[];for(const rm of body.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[];for(const cm of rm[1].matchAll(/<(th|td)\b([^>]*)>([\s\S]*?)<\/\1>/gi)){const value=text(cm[3]);if(value||cells.length)cells.push({text:value,header:cm[1].toLowerCase()==="th",colspan:Number(attr(cm[2],"colspan"))||1,rowspan:Number(attr(cm[2],"rowspan"))||1})}if(cells.length)rows.push({cells})}if(rows.length)out.push({caption,rows})}return out.slice(0,12)}
function extractLinks(html){const links=[],seen=new Set();for(const m of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){const label=text(m[2]),url=absolute(attr(m[1],"href"));if(!label||!url||url.endsWith("#")||seen.has(url)||/^\d{4}[.\-]\d{2}[.\-]\d{2}$/.test(label))continue;seen.add(url);links.push({label,url});if(links.length>=12)break}return links}
function extractImages(html){const images=[],seen=new Set();for(const m of html.matchAll(/<img\b([^>]*)>/gi)){const sourceUrl=absolute(attr(m[1],"src")),match=sourceUrl.match(/sendFileThumbnailTop\.web\?keyValue=(ST\d+)/i),alt=text(attr(m[1],"alt")||"기관 사진");if(!match||seen.has(match[1]))continue;seen.add(match[1]);images.push({url:`${apiBase()}/api/official-image?key=${encodeURIComponent(match[1])}`,sourceUrl,alt});if(images.length>=12)break}return images}
function fieldsFrom(tables){const fields={};for(const row of tables[0]?.rows||[]){if(row.cells.length===2){const key=row.cells[0].text.replace(/\s+/g," "),value=row.cells[1].text;if(key&&value)fields[key]=value}}return fields}
function cleanTables(tables){const seen=new Set(),out=[];for(const table of tables){if(table.rows.every(r=>r.cells.every(c=>!c.text||c.text==="데이터가 존재하지 않습니다.")))continue;const key=table.caption||JSON.stringify(table.rows[0]||{});if(seen.has(key))continue;seen.add(key);out.push(table)}return out}
export default async function handler(req,res){cors(req,res);if(req.method==="OPTIONS")return res.status(204).end();const origin=req.headers.origin||"";if(origin&&!ALLOWED_ORIGINS.has(origin))return res.status(403).json({error:"허용되지 않은 호출 출처입니다."});if(!["GET","POST"].includes(req.method))return res.status(405).json({error:"GET·POST 요청만 지원합니다."});if(rateLimited(req))return res.status(429).json({error:"공단 상세 요청이 많습니다. 잠시 후 다시 시도하세요."});const input=req.method==="GET"?req.query:req.body,id=String(input?.id||"").trim(),type=String(input?.type||"").split(",")[0].trim().toUpperCase(),tab=Number(input?.tab||11);if(!/^\d{11}$/.test(id)||!/^[A-Z]\d{2}$/.test(type)||!TABS.has(tab))return res.status(400).json({error:"기관기호·급여종류·상세 탭을 확인해 주세요."});const key=`${id}|${type}|${tab}`,hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL){res.setHeader("X-Cache","HIT");return res.status(200).json(hit.data)}const params=new URLSearchParams({aTab:String(tab),adminPttnCd:type,ltcAdminSym:id,paymtVltClsfcTypeCd:"",paymtVltClsfcTypeCdSusi:"",paymtVltMgmtNo:"",paymtVltMgmtNo2:"",paymtVltMgmtNoOld:"",showVlt:"Y",vltMgmtYyyy:""}),sourceUrl=`${BASE}${DETAIL_PATH}?${params}`;try{const upstream=await fetch(sourceUrl,{headers:{"User-Agent":"Mozilla/5.0 (compatible; NationwideCareMap/1.0; +https://softm.github.io/nationwide-care-services-map.html)","Accept":"text/html,application/xhtml+xml","Accept-Language":"ko-KR,ko;q=0.9"},signal:AbortSignal.timeout(10000)}),html=await upstream.text();if(!upstream.ok||!html.includes("기관 상세정보"))return res.status(502).json({error:"공단 상세정보를 불러오지 못했습니다."});const tables=cleanTables(extractTables(html)),data={id,type,tab,label:TABS.get(tab),updatedAt:(text(html).match(/최종변경일\s*:\s*([0-9.\-]+)/)||[])[1]||"",fields:tab===11?fieldsFrom(tables):{},tables,links:tab===18?extractLinks(html).filter(x=>/selectBlbdArtiDtl|공지|게시/i.test(x.url)):[],images:tab===18?extractImages(html):[],sourceUrl,fetchedAt:new Date().toISOString()};cache.set(key,{at:Date.now(),data});if(cache.size>240)cache.delete(cache.keys().next().value);res.setHeader("Cache-Control","public, max-age=300, s-maxage=21600, stale-while-revalidate=86400");res.setHeader("X-Cache","MISS");return res.status(200).json(data)}catch(error){return res.status(502).json({error:error?.name==="TimeoutError"?"공단 응답이 지연되고 있습니다. 잠시 후 다시 시도하세요.":"공단 상세정보 연결 중 오류가 발생했습니다."})}}
